import {Tour} from '../tour-component/tour';

export var TOURS: Tour[] = [
  {
      id: 1,
      slug: "the-forgotten-history-of-kakaako",
      title: "The Forgotten History of Kaka’ako ",
      description: "Kaka’ako was once once a thriving community with agricultural terraces, taro plantations, salt ponds and home to docks for foreign ships. Also, many ali’i called this place home. Today, Kaka’ako is one of the fastest growing neighborhoods in all of Oahu. There are several examples of places in Kaka’ako currently undergoing construction and development that can be seen by everyday pedestrians. These recent developments will likely price out many of the people who have called Kaka’ako home and make living their possible for only those who can afford it. Along with the rising cost of living, these new urban developments will destroy the cultural significance and history of Kaka’ako that was once present in the community.",
      place: "hawaii",
      author: "Aaron Falaniko",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 2,
      slug: "big-trouble-in-little-paradise",
      title: "Big Trouble in Little Paradise",
      description: "There is a growing concern with human rights in Hawaii today, which is integrally connected to the impact of tourism on Native Hawaiian’s and their communities. The problem as a whole is tourism, but to be more precise, sports tourism. What’s problematic is how the sports tourism industry seems to have little or no regard to the well-being of the Hawaiian community.",
      place: "hawaii",
      author: "Aaron Sonstein",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 3,
      slug: "decolonization-its-wai-tal",
      title: "Decolonization: It's Wai-tal",
      description: "The Native Hawaiians suffered/continue to suffer a tremendous injustice. The atrocities committed by the American government will sorely be felt throughout many, many generations. One of the more prominent wounds that poses a more significant risk to the future of all of Hawai’i is the misappropriation of natural resources, wai (water) in particular. Due to the utilization of western’s influence in the management of wai in place of traditional, Hawaiian sustainable practices, impending consequences looms around Hawai’i’s future.",
      place: "hawaii",
      author: "Alexis Mukaida",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 4,
      slug: "salt-lake",
      title: "Salt Lake",
      description: "For this tour, I examined my hometown of Salt Lake. I looked at the historical significance of the place from the Hawaiian perspective, as well as it’s history. My central argument is to show the truth of Salt Lake, of how a lake once culturally significant to the Kanaka Maoli was exploited and drained for capitalism, leaving behind a town that primarily favors the settler colonialists and military population.",
      place: "hawaii",
      author: "Allison Cooke",
      twitter: "",
      instagram: "_ascooke",
      web: ""
  },
  {
      id: 5,
      slug: "the-massie-kahahawai-case",
      title: "The Massie-Kahahawai Case",
      description: "The timeline of this case will demonstrate the first injustice, which is the portrayal of the men of \"local\" ethnicity (local Asian and Hawaiian) as being brutes and members of criminal gangs. Even though the men were legally acquitted ... America and the Massie/Fortescue immediately assumed their guilt in the issue - which leads to another injustice.",
      place: "hawaii",
      author: "Angela",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 6,
      slug: "what-happened-to-historic-kailua",
      title: "What Happened to Historic Kailua?",
      description: "Kailua, once a quiet little town, home to families who have lived here for generations, is now a growing city which is built largely upon a flourishing tourism sector and consumer market. While the continuous development and destruction of historic Kailua is primarily an issue for those who were raised there, I believe that it is also of great concern to anyone who appreciates Hawaii’s natural beauty. Tourism is at once Oahu’s greatest downfall and greatest victory, for if we wish to continue to survive economically, we must make the preservation of this place and it’s culture a priority.",
      place: "hawaii",
      author: "Colleen",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 7,
      slug: "militarization-of-oahu",
      title: "Militarization of Oahu",
      description: "There are many places on the island of oahu that show the deep seeds of colonization. Theses areas are painful reminders to native Hawaiians.  Colonization manifests itself in many ways in Hawaii, but the most prevalent way is militarization. Nearly 25% of the island of Oahu is property of the United States Military. While this shows Hawaii's value as a military outpost it also shows the occupying force that exist in current day Hawaii.",
      place: "hawaii",
      author: "",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 8,
      slug: "militarism",
      title: "Militarism",
      description: "The military played a huge role in ancient Hawaii to modern day. Hawaii has been occupied for over 120 years from the United States. It started when Queen Liliuokalani was in power of the Kingdom of Hawaii. She was trying draft a new constitution to restore more power to the native Hawaiians. Soon after that, there was a Coup d’état lead by Lorrin A. Thurston and Sanford B. Dole in 1893.  After this, Kingdom of Hawaii became under control of the US military and Hawaii’s government became the Republic of Hawaii. 4 years later, the Spanish- American war broke out and president Mckinley signed the Joint Resolution which allowed the US to use Hawaii as a military strategic point.",
      place: "hawaii",
      author: "Elmo",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 9,
      slug: "paradise",
      title: "Paradise",
      description: "As today’s world continues to develop and evolve, we can see that certain values and priorities in society are changing as well.  With that, we see a growth in globalization and urbanization.  It is especially prevalent in Hawaii where people all over the world come to partake in this paradise.  However, the price of paradise is paid for the most by those whose voices are heard the least.  Since the overthrow and annexation of the Hawaiian Kingdom, there are numerous examples across the island of Oahu that illustrates how Hawaii has now become a hub for tourism, capitalistic growth, and governmental gain.  The industries that drive the State’s economy have now become a detriment to the Native Hawaiian people whom stories and sacred lands have been lost to capitalistic ideologies and governmental overthrow.",
      place: "hawaii",
      author: "Jacob",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 10,
      slug: "where-the-alii-once-roamed",
      title: "Where the Aliʻi Once Roamed",
      description: "Hawaiʻi was once a thriving kingdom. Upon colonization, Hawaiians were soon forced to conform to a new American lifestyle, giving up their language, losing their nation and having their lands stripped from them. In recent years, Honolulu has been a focal point of tourism to the extent where the mana in certain areas have been lost and will soon be forgotten. We as the people of Hawaiʻi have a duty to preserve our history and culture and may do this by making sure our stories are told the right way. This tour will take you through the streets of Downtown Honolulu; Washington Place, ʻIolani Palace, King  Kamehameha Statue, Aliʻiōlani Hale, Kawaihaʻo Church as well as Waikīkī Beach, Kapīʻolani Park and ʻĀinahau and will explore the significance these places have in Hawaiʻi's History and Culture.",
      place: "hawaii",
      author: "Kamalani",
      twitter: "",
      instagram: "",
      web: "http://missbaquering.weebly.com/pop-tours.html"
  },
  {
      id: 11,
      slug: "living-in-kakaako-where-friendships-last-forever",
      title: "Living in Kaka'ako: Where friendships last forever...",
      description: "Before Hawai'i became a state, Kaka'ako was composed of campsites for people of many ethnicities. Most of them were poor, and they trusted one another. In the book, Kaka'ako As We Knew It, author Marsha Gibson describes her experiences living in Kaka'ako and how she was able to create long lasting friendships. Land plays an important role in helping people build friendships. Kaka'ako is a unique place that has the potential to empower its residents. My project emphasizes the need for community members to organize and work together in order to help houseless families thrive in Kaka'ako. Each of us can be a leader in our own way that will end the houselessness cycle in our communities.",
      place: "hawaii",
      author: "Kathleen",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 12,
      slug: "think-local-hawaii",
      title: "THINK LOCAL HAWAII!",
      description: "This POP Tour/Interactive map seeks to provide individuals with information on the various local farms, fishponds, etc of Oʻahu that are working to provide Hawaiʻi and its residents with locally grown products as well as the specific places that are dedicated to selling these products in an effort to push individuals to THINK LOCAL!",
      place: "hawaii",
      author: "Keanu Bulseco",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 13,
      slug: "food-sustainability-in-hawaii",
      title: "Food Sustainability in Hawai'i",
      description: "The Office of Planning Department of Business Economic Development and Tourism’s Increased Food Security and Food Self-Sufficiency Strategy states that “about 85-90 percent of Hawai’i’s food is imported, which makes it particularly vulnerable to natural disasters and global event that might disrupt shipping and the food supply.” Before western contacts Hawaii thrived in food production by fish farming, lo'i patches, and fruit/vegetable crop cultivation. Current health problems are due to the expansion, over population and development of colonialism. Most diets consist of canned and processed food (oppression) which leads Hawaiians and non-Hawaiians alike to obesity and other health issues. “Hawai’i’ s agriculture seems to be experiencing a renaissance recently, with more public attention towards supporting local farmers- Dela Cruz-Talbert” (Yamashiro, Goodyear-Ka’opua, 2014) “See I am a farmer, holding strength and determination in my left hand, a pick and a pen in my right; while love, respect and the willingness to work reside in my heart.-Uilani Arasato” From as small as our own aquaponics system to a large restoration of a fishpond, we all have our Kuleana (responsibility) to provide for our future!!",
      place: "hawaii",
      author: "Kehau Pelekai",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 14,
      slug: "from-giving-life-to-dumping-waste",
      title: "From Giving Life to Dumping Waste",
      description: "In Hawaii, some of us we believe that Kane and Kanaloa could open fountains and pools all over the island. When they arrived at the head of Manoa valley Kanaloa was amazed at the awa, though he didn’t know where to find water. Kane said the hillside and struck the ground with his staff. Clear cool, water came and nestled between the fallen stones. The way the Hawaiians respected the land for giving life is not how it is today. The river water is mixed with our waste then dumped into the oceans we swim, fish and play in. ",
      place: "hawaii",
      author: "Lauren",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 15,
      slug: "hawaiis-worst-mistake",
      title: "Hawaii's Worst Mistake",
      description: "Waikiki is the mecca for tourism in Hawaii. This was not always the case. It was once filled with lush green lo'i that sustained a great deal of people. Since the urbanization and construction of Waikiki in the early 20th century Waikiki has created a lifestyle that has proven to be detrimental to not only O'ahu, but Hawaii as a whole.",
      place: "hawaii",
      author: "Namakana",
      twitter: "",
      instagram: "maaakana",
      web: ""
  },
  {
      id: 16,
      slug: "restore-historical-ewa",
      title: "Restore Historical Ewa",
      description: "Ewa Beach has transitioned from a sugar cane plantation to a suburban center with booming restate. The issue that I will be addressing in this POP Tour is how the history of Ewa has been overwritten with development. I am curious to explore what was here before now.",
      place: "hawaii",
      author: "Natalie Hajinelian",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 17,
      slug: "militarization-of-hawaii",
      title: "Militarization Of Hawaii",
      description: "The Islands of Hawaii have always had a complex and interesting history when it comes to war and military affairs. In this tour, the stops you will visit will serve as examples of how the militarization of Oahu has affected the island both socially and physically. In addition this tour will show how, Hawaii's development and political background has changed due to the introduction and expansion of the military.",
      place: "hawaii",
      author: "Nathan",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 18,
      slug: "kakaako-houselessness-luxury-development",
      title: "KAKA’AKO: Houselessness & Luxury Development",
      description: "Please start the tour at Ala Moana Beach Park and end at The Hawai’i Community Development Authority (HCDA). Everything in the middle is up to you! Please be respectful of the community and its residents. Houseless is a term which is used in place of homeless. Hawai’i is their home, they just don’t have a house.",
      place: "hawaii",
      author: "Nick Ishii",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 19,
      slug: "pop-tour-of-paradise",
      title: "PoP Tour of Paradise",
      description: "This PoP Tour attempts to challenge the point of view of Hawaii as a paradise as seen from the perspective of the average person living in or visiting Hawaii. There are many people who are marginalized by society, and sometimes we don’t even realize how we are oppressing them. I chose to focus on the houseless, and to try to show the system through their eyes as much as I could.",
      place: "hawaii",
      author: "Reid Oshiro",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 20,
      slug: "houselessness-in-hawaii",
      title: "Houselessness in Hawaii",
      description: "Hawaii is faced with a dire houselessness problem. It has the highest houselessness rate in the nation, and its efforts to address this issue have largely been ineffective. Rather than criminalizing poverty as it has done in the past, Hawaii must treat its houseless population with compassion and dignity if it is to live up to its reputation as the Aloha State. This tour will guide viewers around downtown Honolulu to observe some of the key entities and locations that compose Hawaii's response to the issue of houselessness.",
      place: "hawaii",
      author: "Reyn",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 21,
      slug: "nani-kaneohe",
      title: "Nani Kaneohe",
      description: "Kaneohe has some of the most beautiful hikes in the world but unknowing to most, it is being over run by invasive plants.  We need to educate the populous on the history of the forest and show people how they can get involved to help care for the land.  My POP tour showcases some of Kaneohe’s best hikes while showing the truth behind most of these plants.",
      place: "hawaii",
      author: "Richard Lindley",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 22,
      slug: "good-ol-kalihi",
      title: "Good ol’Kalihi.",
      description: "From the early 1900s, Kalihi was developed in being Honolulu’s first multi-ethnic affordable residential community. Over the years, Kalihi faced a great amount of change from being an agrarian to an urban, industrialized and commercial community. Kalihi used to be a district that was only had farms, open land, small business and affordable homes. As of today, the City and County of Honolulu plans to revitalize the Kalihi area with rezoning land to accommodate with Honolulu Authority Rapid Transportation. As a person from Kalihi, I am sadden and devastated of the rail. As my grandpa said “Kalihi wasn’t meant for a scenery of concrete. It is just so sad of what is to come.”",
      place: "hawaii",
      author: "Shai",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 23,
      slug: "the-corners-of-paradise",
      title: "The Corners of Paradise",
      description: "For my project I wanted to put together a tour that acted like an actual commercial tour. It seems that it is the opinion of the tourists that both the public and private sectors seem to cater to the most. So I aimed my Politics of Place Tour on houselessness and settler colonialism at tourists. My argument is to show that the government is not dealing with the problem, but masking it. I hope you find it informative with an interesting twist. This is also a shortened version of the final project. Please take everything I say with a grain of salt.",
      place: "hawaii",
      author: "Shin",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 24,
      slug: "effects-of-tourism-capitalism-in-hawaii",
      title: "Effects of Tourism/Capitalism In Hawaii",
      description: "",
      place: "hawaii",
      author: "Takashi Murayama",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 25,
      slug: "kailua-exclusive-friend-of-the-upper-class",
      title: "Kailua: Exclusive Friend of the Upper Class",
      description: "In 1995 the year I was born, the median price of a single family house in Hawaii was $385,000.  Now days the average house costs about $924,500 (locationshawaii.com). This largely due to the widespread gentrification of the island, which includes my home town of Kailua. I remember how my favorite beach was always easy to access and the friendly easy going local people community that I was accustomed to.  Kailua is now seen as a hub for tourist and expensive place that most people living here can’t afford. Most of the Middle and poor classes are continually trying to be phased out and replace with richer neighborhoods. This is very similar to the exact definition of gentrification as the Webster dictionary states. I have major doubts that this once small town will not be turned in to a second more exclusive version of Waikiki. People need to know about what is going on here because if this continues to go unchecked it will spread to the rest of the smaller Island towns and eliminate the small community like island vibe this place to have. Therefore, the point of this Project is to inform people about what is happening in my home town in hopes that they will take action to stop this spread by supporting local industries and speaking out against development.",
      place: "hawaii",
      author: "Troy Peiler",
      twitter: "",
      instagram: "",
      web: ""
  },
  {
      id: 26,
      slug: "big-island-plantation-contamination-driving-tour",
      title: "Big Island Plantation Contamination Driving Tour",
      description: "Sugar production on Hawaii Island's Hamakua Coast may have ended over two decades ago, but the industry left its marks on the land there. One of the scars that's hard to see but remains dangerous is the presence of chemicals such as arsenic and DDT in the soil. Leftover from pesticide use in the last century, these chemicals pose a risk to humans and the environment. This tour shows where some of these sites are and how locals, especially in small communities, are using the land today.",
      place: "hawaii",
      author: "Alex Bitter",
      twitter: "",
      instagram: "",
      web: "https://alexbitter.atavist.com/big-island-plantation-contamination-driving-tour"
  },
];
